{{- if .Values.global.mepagent.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appconfig.aksk.secretname }}
  namespace: {{ .Values.appconfig.appnamespace }}
type: Opaque
immutable: true
stringData: 
  accesskey: {{ quote .Values.appconfig.aksk.accesskey }}
  secretkey: {{ quote .Values.appconfig.aksk.secretkey }}
  appInsId: {{ quote .Values.appconfig.aksk.appInsId }}
{{- end }}