global:
  mepagent:
    enabled: false
    configmapname: <CONFIGMAP_NAME>
  namespace:
    enabled: false

appconfig:
  appnamespace: default
  aksk:
    secretname: <random_value>
    accesskey: <akvalue>
    secretkey: <skvalue>
    appInsId: <idvalue>

serviceconfig:
#  - servicename: positioning-service
#    port: 9997
#    version: 1.0
#    protocol: HTTP
#    appnamespace: default
imagelocation:
  domainname: swr.ap-southeast-1.myhuaweicloud.com
  project: edgegallery